# In-memory product catalog only. No MongoDB or persistent storage is used.
PRODUCT_CATALOG = [
    {
        "id": "p1",
        "name": "White Sneakers",
        "category": "footwear",
        "tags": ["sneakers", "white", "casual", "sport"],
        "style": ["streetwear", "minimal"],
        "color": "White",
    },
    {
        "id": "p2",
        "name": "Grey Cargo Pants",
        "category": "bottom",
        "tags": ["cargo", "grey", "utility", "street"],
        "style": ["streetwear", "casual"],
        "color": "Grey",
    },
    {
        "id": "p3",
        "name": "Blue Denim Jeans",
        "category": "bottom",
        "tags": ["denim", "blue", "classic"],
        "style": ["casual", "smart-casual"],
        "color": "Blue",
    },
    {
        "id": "p4",
        "name": "Black Tapered Jeans",
        "category": "bottom",
        "tags": ["jeans", "black", "slim"],
        "style": ["minimal", "streetwear"],
        "color": "Black",
    },
    {
        "id": "p5",
        "name": "Beige Chinos",
        "category": "bottom",
        "tags": ["chino", "beige", "formal-casual"],
        "style": ["smart-casual", "semi-formal"],
        "color": "Beige",
    },
    {
        "id": "p6",
        "name": "Navy Blue Shirt",
        "category": "top",
        "tags": ["shirt", "navy", "solid"],
        "style": ["smart-casual", "formal"],
        "color": "Navy",
    },
    {
        "id": "p7",
        "name": "Grey Joggers",
        "category": "bottom",
        "tags": ["jogger", "grey", "athleisure"],
        "style": ["sport", "casual"],
        "color": "Grey",
    },
    {
        "id": "p8",
        "name": "Silver Watch",
        "category": "accessory",
        "tags": ["watch", "silver", "minimal"],
        "style": ["formal", "minimal"],
        "color": "Silver",
    },
]
